'use client';
import {useState} from 'react';
import type {Video} from '../seed';
import BrandLogo from '../brand-logo';
export default function IntegrationFields({video,onChange,disabled}:{video:Video;onChange:(value:Partial<Video>)=>void;disabled:boolean}){
 const [website,setWebsite]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function lookup(){const name=video.brandName?.trim();if(!name)return;setLoading(true);setError('');try{const r=await fetch('/api/brand',{method:'POST',headers:{'Content-Type':'application/json','x-studio-request':'1'},body:JSON.stringify({name,website})});const d=await r.json() as {logo:string;error?:string;warning?:string};if(!r.ok)throw Error(d.error);onChange({brandLogo:d.logo});setError(d.warning||'')}catch(e){setError(e instanceof Error?e.message:'Logo lookup failed.')}finally{setLoading(false)}}
 async function upload(file:File|undefined){if(!file)return;setLoading(true);setError('');try{const form=new FormData();form.set('file',file);const r=await fetch('/api/upload',{method:'POST',headers:{'x-studio-request':'1'},body:form});const d=await r.json() as {url:string;error?:string};if(!r.ok)throw Error(d.error);onChange({brandLogo:d.url})}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setLoading(false)}}
 return <fieldset className="integration-fields" disabled={disabled||loading}><legend>Brand integration <span className="muted">· optional</span></legend><label className="check"><input type="checkbox" checked={!!video.brandIntegrated} onChange={e=>onChange({brandIntegrated:e.target.checked})}/>This video includes a brand integration</label>{video.brandIntegrated&&<><label>Brand name<input value={video.brandName||''} list="integration-brands" onChange={e=>{onChange({brandName:e.target.value,brandLogo:''});setError('')}} onBlur={lookup} required maxLength={100} placeholder="e.g. CeraVe"/></label><datalist id="integration-brands">{['CeraVe','Black & White','Airtel'].map(b=><option key={b} value={b}/>)}</datalist><label>Brand website <span className="muted">(helps find new brands)</span><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="brand.com"/></label><button type="button" className="secondary-button" onClick={lookup}>{loading?'Finding logo…':'Fetch logo'}</button>{video.brandLogo&&<div className="integration-preview"><BrandLogo name={video.brandName||'Brand'} logo={video.brandLogo}/><p>Shown with this video and in your brands section.</p></div>}{error&&<p className="hint" role="status">{error}</p>}<details><summary>Use another logo</summary><label>Logo image URL<input value={video.brandLogo||''} onChange={e=>onChange({brandLogo:e.target.value})}/></label><label>Or upload a logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label></details></>}</fieldset>
}
