import {youtubeKey,officialYoutubeViews} from '../youtube-statistics.js';
import {authorized,content,cookie,credentials,database,digest,imageUrl,passwordHash,profileUrl,random,runtime,sameOrigin,seed,sessionToken,UserError,verifyPassword} from '../server.js';
import {fetchProfile,importVideo,parseVideo} from '../import-video.js';
import type {Video} from '../seed.js';
import {resolveBrand} from '../brand-service.js';
import {refreshViews,refreshVideoViews} from '../view-counts.js';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200,headers:Record<string,string>={})=>Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
async function body(req:Request){const text=await req.text();if(text.length>24000)throw new UserError('This entry is too large.',413);try{return JSON.parse(text)}catch{throw new UserError('Invalid request.')}}
async function handle(req:Request){try{const parsedUrl=new URL(req.url);const path=parsedUrl.searchParams.get('path')||parsedUrl.pathname.replace(/^\/api\//,'');const method=req.method;
 if(path.startsWith('media/')&&method==='GET'){const key=path.slice(6);if(!/^[a-f0-9]{64}\.(jpg|png|webp)$/.test(key))return json({error:'Not found'},404);const object=await runtime().BUCKET.get(key);if(!object)return json({error:'Not found'},404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}})}
 if(path==='stats'&&method==='GET')return json(await refreshViews());
 if(path==='content'&&method==='GET')return json(await content());
 if(path==='session'&&method==='GET')return json({authenticated:await authorized(req)});
 if(method!=='GET')sameOrigin(req);
 if(path==='login'&&method==='POST'){await seed();const db=database(),data=await body(req),now=Date.now();if(typeof data.username!=='string'||typeof data.password!=='string'||data.password.length>256)throw new UserError('Incorrect username or password.',401);const key=await digest('login:'+(req.headers.get('x-vercel-forwarded-for')?.split(',')[0]||req.headers.get('x-real-ip')||'local'));await db.prepare('INSERT INTO attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN attempts.expires<? THEN 1 ELSE attempts.count+1 END,expires=CASE WHEN attempts.expires<? THEN CAST(? AS BIGINT) ELSE attempts.expires END').bind(key,now+900000,now,now,now+900000).run();const rate=await db.prepare('SELECT count FROM attempts WHERE key=?').bind(key).first<{count:number}>();if((rate?.count||0)>10)throw new UserError('Too many attempts. Please wait 15 minutes.',429);const saved=await credentials();if(!saved.hash)throw new UserError('Studio sign-in has not been configured.',503);const valid=await verifyPassword(data.password,saved.hash);if(!valid||data.username!==saved.username)throw new UserError('Incorrect username or password.',401);const token=random();await db.batch([db.prepare('INSERT INTO sessions (hash,expires) VALUES (?,?)').bind(await digest(token),now+28800000),db.prepare('DELETE FROM sessions WHERE expires<?').bind(now),db.prepare('DELETE FROM attempts WHERE key=? OR expires<?').bind(key,now)]);return json({ok:true},200,{'Set-Cookie':cookie(req,token)})}
 if(!await authorized(req))throw new UserError('Please sign in to the studio.',401);
 if(path==='youtube-connection'&&method==='GET')return json({connected:!!await youtubeKey()});
 if(path==='youtube-connection'&&method==='POST'){const d=await body(req);if(typeof d.key!=='string'||!/^[-A-Za-z0-9_]{20,200}$/.test(d.key.trim()))throw new UserError('Enter a valid YouTube Data API key.');const key=d.key.trim();await officialYoutubeViews('5YBHLwNuM9Y',key);await database().prepare("INSERT INTO settings (key,value) VALUES ('youtube-api-key',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key).run();try{return json({connected:true,...await refreshViews(true,true)})}catch{return json({connected:true,warning:'Connection saved. Use Refresh view counts to retry fetching the totals.'})}}
 if(path==='brand'&&method==='POST'){const d=await body(req);return json(await resolveBrand(d.name,d.website||''))}
 if(path==='stats'&&method==='POST')return json(await refreshViews(true));
 if(path==='logout'&&method==='POST'){await database().prepare('DELETE FROM sessions WHERE hash=?').bind(await digest(sessionToken(req))).run();return json({ok:true},200,{'Set-Cookie':cookie(req,'',0)})}
 if(path==='import'&&method==='POST'){const d=await body(req);if(typeof d.url!=='string'||d.url.length>3000)throw new UserError('Paste a video URL.');return json(await importVideo(d.url))}
 if(path==='profile'&&method==='POST'){const d=await body(req);return json(await fetchProfile(d.url))}
 if(path==='upload'&&method==='POST'){if(Number(req.headers.get('content-length')||0)>3500000)throw new UserError('Choose an image under 3 MB.',413);const form=await req.formData(),file=form.get('file');if(!(file instanceof File)||file.size>3000000||file.size===0)throw new UserError('Choose an image under 3 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let ext='',mime='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){ext='jpg';mime='image/jpeg'}else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){ext='png';mime='image/png'}else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'){ext='webp';mime='image/webp'}else throw new UserError('Upload a JPG, PNG, or WebP image.');const key=random()+'.'+ext;await runtime().BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});return json({url:'/api/media/'+key})}
 if(path==='videos'&&(method==='POST'||method==='PUT')){const d=await body(req),parsed=parseVideo(d.url);if(!['Long-form','Shorts','Reels'].includes(d.category))throw new UserError('Choose a video category.');if(typeof d.title!=='string'||!d.title.trim()||d.title.length>500||typeof d.clientName!=='string'||!d.clientName.trim()||d.clientName.length>200)throw new UserError('Add a title and client name.');const thumb=imageUrl(d.thumbnail);if(!thumb)throw new UserError('Add a thumbnail URL or upload an image.');const v:Video={...parsed,category:d.category,title:d.title.trim(),tag:typeof d.tag==='string'?d.tag.trim().slice(0,100):'',thumbnail:thumb,clientName:d.clientName.trim(),clientUrl:profileUrl(d.clientUrl),clientImage:imageUrl(d.clientImage),featured:!!d.featured,brandIntegrated:!!d.brandIntegrated};if(v.brandIntegrated){if(typeof d.brandName!=='string'||!d.brandName.trim()||d.brandName.length>100)throw new UserError('Enter the integration brand name.');v.brandName=d.brandName.trim();v.brandLogo=imageUrl(d.brandLogo);if(!v.brandLogo)v.brandLogo=(await resolveBrand(v.brandName!)).logo;if(!v.brandLogo)throw new UserError('Fetch or upload the brand logo before publishing this integration.');}const db=database();if(method==='POST'){if(await db.prepare('SELECT id FROM videos WHERE id=?').bind(v.id).first())throw new UserError('This video is already in your portfolio. Edit its existing entry.',409);await db.prepare('INSERT INTO videos (id,data,created) VALUES (?,?,?)').bind(v.id,JSON.stringify(v),Date.now()).run()}else{const result=await db.prepare('UPDATE videos SET data=? WHERE id=?').bind(JSON.stringify(v),v.id).run();if(!result.meta.changes)throw new UserError('This video no longer exists.',404)}if(method==='POST'){let viewsRefreshed=false;try{viewsRefreshed=await refreshVideoViews(v)}catch{console.error('Published video view refresh failed')}return json({ok:true,viewsRefreshed})}return json({ok:true})}
 if(path.startsWith('videos/')&&method==='DELETE'){const id=decodeURIComponent(path.slice(7));await database().prepare('DELETE FROM videos WHERE id=?').bind(id).run();return json({ok:true})}
 if(path==='settings'&&method==='PUT'){const d=await body(req);if(!Array.isArray(d.brands)||d.brands.length>30||d.brands.some((b:unknown)=>typeof b!=='string'||b.length>100)||typeof d.bio!=='string'||d.bio.length>3000||typeof d.email!=='string'||(d.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))||d.email.length>254)throw new UserError('Check your profile details and email address.');const logos:Record<string,string>={};if(d.brandLogos&&typeof d.brandLogos==='object')for(const [name,url] of Object.entries(d.brandLogos).slice(0,40)){if(name.length<=100&&imageUrl(url))logos[name]=imageUrl(url)}const settings={brandLogos:logos,brands:[...new Set(d.brands.map((s:string)=>s.trim()).filter(Boolean))],bio:d.bio,email:d.email,instagram:profileUrl(d.instagram)};await database().prepare("INSERT INTO settings (key,value) VALUES ('public',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(settings)).run();return json({ok:true})}
 if(path==='password'&&method==='PUT'){const d=await body(req);if(typeof d.currentPassword!=='string'||typeof d.password!=='string'||d.password.length<12||d.password.length>128||typeof d.username!=='string'||!/^[-\w.@]{3,60}$/.test(d.username))throw new UserError('Use a username of 3–60 letters, numbers, or . @ _ -, and a password of 12–128 characters.');const saved=await credentials();if(!await verifyPassword(d.currentPassword,saved.hash))throw new UserError('Current password is incorrect.',401);await database().batch([database().prepare("INSERT INTO settings (key,value) VALUES ('credentials',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify({username:d.username,hash:await passwordHash(d.password)})),database().prepare('DELETE FROM sessions')]);return json({ok:true},200,{'Set-Cookie':cookie(req,'',0)})}
 return json({error:'Not found'},404);
 }catch(error){if(error instanceof UserError)return json({error:error.message},error.status);console.error('Studio request failed',error instanceof Error?error.message:'Unknown error');return json({error:'This service is temporarily unavailable. Your changes have not been saved. Please try again.'},503)}}
export {handle as GET,handle as POST,handle as PUT,handle as DELETE};
