import {runtime,UserError,profileUrl,imageUrl} from './server';
import type {Video} from './seed';
export function parseVideo(raw:string){let u:URL;try{u=new URL(raw)}catch{throw new UserError('Paste a valid YouTube or Instagram video link.')}if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port)throw new UserError('Use a public YouTube or Instagram link.');const host=u.hostname.toLowerCase();if(['youtu.be','www.youtube.com','youtube.com','m.youtube.com'].includes(host)){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed|live)\/([^/]+)/)?.[1];if(!id||!/^[-\w]{11}$/.test(id))throw new UserError('This is a channel link. Paste a link to an individual video.');const short=u.pathname.startsWith('/shorts/');return {id,platform:'youtube' as const,category:short?'Shorts' as const:'Long-form' as const,url:`https://www.youtube.com/${short?'shorts/':'watch?v='}${id}`}}if(['www.instagram.com','instagram.com'].includes(host)){const m=u.pathname.match(/^\/(reel|reels|p)\/([A-Za-z0-9_-]{5,100})(?:\/|$)/);if(m)return {id:m[2],platform:'instagram' as const,category:'Reels' as const,url:`https://www.instagram.com/${m[1]==='p'?'p':'reel'}/${m[2]}/`}}throw new UserError('Supported links: YouTube videos, YouTube Shorts, and Instagram reels or video posts.')}
async function remote(url:string){const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(9000),headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'en-US,en;q=0.8'}});if(!r.ok)throw Error('Metadata unavailable');return r}
function decode(s:string){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function meta(html:string,key:string){const tags=html.match(/<meta\b[^>]*>/gi)||[];for(const tag of tags){if(tag.includes(`"${key}"`)||tag.includes(`'${key}'`)){const m=tag.match(/content=["']([^"']*)["']/i);if(m)return decode(m[1])}}return ''}
export async function fetchProfile(raw:string){const url=profileUrl(raw);if(!url)throw new UserError('Use a YouTube channel or Instagram profile URL.');try{const html=await (await remote(url)).text();const name=meta(html,'og:title').replace(/ - YouTube$/,'').replace(/ • Instagram.*$/,'');return {clientName:name,clientUrl:url,clientImage:imageUrl(meta(html,'og:image'))}}catch{return {clientName:'',clientUrl:url,clientImage:''}}}
export async function importVideo(raw:string){const parsed=parseVideo(raw);const video:Video={...parsed,title:'',thumbnail:parsed.platform==='youtube'?`https://i.ytimg.com/vi/${parsed.id}/hqdefault.jpg`:'',clientName:'',clientUrl:'',clientImage:'',featured:false};const warnings:string[]=[];
 if(parsed.platform==='youtube'){try{const data=await (await remote(`https://www.youtube.com/oembed?url=${encodeURIComponent(parsed.url)}&format=json`)).json() as {title:string;author_name:string;author_url:string;thumbnail_url:string};video.title=data.title;video.clientName=data.author_name;video.clientUrl=profileUrl(data.author_url);video.thumbnail=imageUrl(data.thumbnail_url)||video.thumbnail;if(video.clientUrl){const profile=await fetchProfile(video.clientUrl);video.clientImage=profile.clientImage}}catch(error){console.error('YouTube metadata:',String(error));warnings.push('YouTube did not return the title or channel. The thumbnail is ready; fill in any missing details.')}}else{try{const token=runtime().INSTAGRAM_ACCESS_TOKEN;if(token){const d=await (await remote(`https://graph.facebook.com/v25.0/instagram_oembed?url=${encodeURIComponent(parsed.url)}&access_token=${encodeURIComponent(token)}`)).json() as {title:string;thumbnail_url:string;author_name:string;author_url:string};video.title=d.title||'';video.thumbnail=imageUrl(d.thumbnail_url);video.clientName=d.author_name||'';video.clientUrl=profileUrl(d.author_url)}else{const html=await (await remote(parsed.url)).text();video.thumbnail=imageUrl(meta(html,'og:image'));video.title=meta(html,'og:title');const author=html.match(/"owner"\s*:\s*\{[^}]*"username"\s*:\s*"([^"\\]+)"/);if(author){video.clientName=author[1];video.clientUrl=profileUrl('https://www.instagram.com/'+author[1])}}if(video.clientUrl)video.clientImage=(await fetchProfile(video.clientUrl)).clientImage}catch{}if(!video.thumbnail||!video.clientName)warnings.push('Instagram limits automatic previews. Add the missing thumbnail and client details before publishing.');}
 if(!video.clientImage)warnings.push('The profile picture was not available. You can upload it or add its image URL.');return {video,warnings};}
