import {initialVideos,initialSettings,type Video} from './seed.js';
import {brandKey,knownBrand} from './brand-catalog.js';
let videos=initialVideos,settings=initialSettings,format='All',client='',style='',brand='',revision=0;
const $=(id:string)=>document.getElementById(id)!;
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,className='',text='')=>{const n=document.createElement(tag);n.className=className;n.textContent=text;return n};
function image(src:string,alt:string,className=''){const n=el('img',className);n.src=src;n.alt=alt;n.loading='lazy';n.addEventListener('error',()=>{n.hidden=true},{once:true});return n}
function logo(name:string,url?:string){const wrap=el('span','brand-logo');const src=url||knownBrand(name)?.logo;if(src)wrap.append(image(src,name+' logo'));wrap.append(el('span','',name));return wrap}
const brandId=(name:string)=>brandKey(knownBrand(name)?.name||name);
function showPortfolio(){const section=$('portfolio');section.tabIndex=-1;section.focus({preventScroll:true});section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
const clientId=(v:Video)=>v.clientUrl||v.clientName;
let frame=0,previousCount=0;
function renderViews(){$('totalProjects').textContent=videos.length.toLocaleString('en-US');cancelAnimationFrame(frame);const known=videos.filter(v=>typeof v.views==='number'),total=known.reduce((n,v)=>n+v.views!,0),target=$('totalViews');target.setAttribute('aria-label',total.toLocaleString('en-US')+' views');$('countCoverage').textContent=known.length+' of '+videos.length+' videos counted';const start=performance.now(),from=previousCount;previousCount=total;function tick(now:number){const t=Math.min(1,(now-start)/1200);target.textContent=Math.round(from+(total-from)*(1-(1-t)**3)).toLocaleString('en-US');if(t<1)frame=requestAnimationFrame(tick)}if(matchMedia('(prefers-reduced-motion: reduce)').matches)target.textContent=total.toLocaleString('en-US');else frame=requestAnimationFrame(tick)}
function renderCards(){const grid=$('portfolioGrid');grid.replaceChildren();const shown=videos.filter(v=>(format==='All'||v.category===format)&&(!client||clientId(v)===client)&&(!style||v.tag===style)&&(!brand||(v.brandIntegrated&&brandId(v.brandName||'')===brandId(brand))));const status=$('brandFilterStatus');status.hidden=!brand;$('brandFilterLabel').textContent=brand?brand+' · '+shown.length+' '+(shown.length===1?'video':'videos'):'';for(const v of shown){const card=el('button','video-card visible');card.type='button';card.setAttribute('aria-label','Play '+v.title);const thumb=el('div','video-thumb');thumb.append(image(v.thumbnail,v.title));thumb.append(el('div','thumb-overlay'));thumb.append(el('span','play-btn','▶'));const info=el('div','video-info');info.append(el('div','video-category',[v.category,v.tag,v.clientName].filter(Boolean).join(' · ')),el('div','video-title',v.title));if(v.brandIntegrated&&v.brandName){const badge=el('div','integration-badge');badge.append(logo(v.brandName,v.brandLogo),el('span','','Brand integration'));info.append(badge)}card.append(thumb,info);card.addEventListener('click',()=>openVideo(v));grid.append(card)}if(!shown.length)grid.append(el('p','empty-state','No videos match these filters.'));}
function render(){
 $('profileBio').textContent=settings.bio;
 const email=$('contactEmail') as HTMLAnchorElement;email.textContent=settings.email;email.href='mailto:'+settings.email;email.hidden=!settings.email;
 const instagram=$('profileInstagram') as HTMLAnchorElement;instagram.hidden=!settings.instagram;if(settings.instagram)instagram.href=settings.instagram;
 const tabs=$('filterTabs');tabs.replaceChildren();for(const value of ['All','Long-form','Shorts','Reels']){const button=el('button','filter-btn'+(format===value?' active':''),value);button.onclick=()=>{format=value;render()};tabs.append(button)}
 const select=$('clientFilter') as HTMLSelectElement;select.replaceChildren(new Option('All clients',''));const clients=new Map<string,Video>();for(const v of videos){const old=clients.get(clientId(v));if(!old||(!old.clientImage&&v.clientImage))clients.set(clientId(v),v)}for(const [id,v] of clients)select.add(new Option(v.clientName,id));if(!clients.has(client))client='';select.value=client;
 const styles=$('styleFilter') as HTMLSelectElement;styles.replaceChildren(new Option('All styles',''));for(const s of new Set(videos.map(v=>v.tag).filter(Boolean)))styles.add(new Option(s!,s));styles.value=style;
 const brands=$('brandLogos');brands.replaceChildren();const integrations=videos.filter(v=>v.brandIntegrated&&v.brandName);
 const names=new Map<string,string>();for(const name of [...settings.brands,...integrations.map(v=>v.brandName!)])if(!names.has(brandId(name)))names.set(brandId(name),name);
 if(brand&&!names.has(brandId(brand)))brand='';
 for(const [id,name] of names){const button=el('button','brand-filter');button.type='button';button.setAttribute('aria-label','Show '+name+' videos');button.setAttribute('aria-pressed',String(!!brand&&brandId(brand)===id));button.setAttribute('aria-controls','portfolioGrid');button.append(logo(name,integrations.find(v=>brandId(v.brandName!)===id)?.brandLogo||settings.brandLogos[name]));button.onclick=()=>{brand=name;format='All';client='';style='';render();showPortfolio()};brands.append(button)}
 const clientGrid=$('clientGrid');clientGrid.replaceChildren();for(const [id,v] of clients){const button=el('button','client-card');if(v.clientImage)button.append(image(v.clientImage,v.clientName));else button.append(el('span','client-initial',v.clientName[0]));button.append(el('strong','',v.clientName),el('small','',videos.filter(x=>clientId(x)===id).length+' edits'));button.onclick=()=>{client=id;format='All';style='';brand='';render();$('portfolio').scrollIntoView({behavior:'smooth'})};clientGrid.append(button)}
 const strip=$('reelStrip');strip.replaceChildren();const featured=videos.filter(v=>v.featured),reel=featured.length?featured:videos.slice(0,8);for(const v of [...reel,...reel]){const item=el('button','reel-item');item.setAttribute('aria-label','Play '+v.title);const inner=el('div','reel-item-inner');inner.append(image(v.thumbnail,''));item.append(inner);item.onclick=()=>openVideo(v);strip.append(item)}
 renderCards();renderViews();}
let focusBefore:HTMLElement|null=null;const modal=$('videoModal');
function closeModal(){modal.classList.remove('open');$('modalVideoWrap').replaceChildren();document.body.style.overflow='';focusBefore?.focus()}
Object.assign(window,{closeModal});
function openVideo(v:Video){focusBefore=document.activeElement as HTMLElement;const wrap=$('modalVideoWrap');wrap.replaceChildren();wrap.classList.toggle('portrait',v.category!=='Long-form');const iframe=el('iframe');iframe.src=v.platform==='youtube'?'https://www.youtube.com/embed/'+encodeURIComponent(v.id)+'?autoplay=1&rel=0':'https://www.instagram.com/'+(v.url.includes('/reel/')?'reel':'p')+'/'+encodeURIComponent(v.id)+'/embed/';iframe.title=v.title;iframe.allow='autoplay; encrypted-media; fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';wrap.append(iframe);modal.classList.add('open');document.body.style.overflow='hidden';(modal.querySelector('button')||modal).focus()}
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});modal.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Tab'){const nodes=Array.from(modal.querySelectorAll<HTMLElement>('button,iframe'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
$('clearBrandFilter').onclick=()=>{brand='';format='All';client='';style='';render();showPortfolio()};
$('clientFilter').onchange=e=>{client=(e.target as HTMLSelectElement).value;renderCards()};$('styleFilter').onchange=e=>{style=(e.target as HTMLSelectElement).value;renderCards()};
async function refresh(stats=false){const current=++revision;try{const r=await fetch('/api/content');if(!r.ok)throw Error();const d=await r.json();if(current!==revision)return;videos=d.videos;settings=d.settings;render();$('workStatus').textContent='';if(stats){const r=await fetch('/api/stats');if(r.ok){const d=await r.json();if(current===revision){videos=d.videos;renderViews()}}}}catch{if(current===revision)$('workStatus').textContent='Showing saved work. Live updates are temporarily unavailable.'}}
if(typeof BroadcastChannel!=='undefined'){const c=new BroadcastChannel('portfolio-updates');c.onmessage=()=>{void refresh()}}
window.addEventListener('focus',()=>{void refresh()});render();void refresh(true);
