import {db,media} from './database.js';
import {initialVideos,initialSettings} from './seed.js';
import {withViews} from './view-counts.js';
export const runtime=()=>({DB:db,BUCKET:media,ADMIN_USERNAME:process.env.ADMIN_USERNAME,ADMIN_PASSWORD_HASH:process.env.ADMIN_PASSWORD_HASH,INSTAGRAM_ACCESS_TOKEN:process.env.INSTAGRAM_ACCESS_TOKEN});
export function database(){const db=runtime().DB;if(!db)throw new Error('Storage is unavailable. Please try again shortly.');return db}
export async function seed(){const db=database();if(await db.prepare("SELECT key FROM settings WHERE key='initialized'").first())return;await db.batch([...initialVideos.map((v,i)=>db.prepare("INSERT INTO videos (id,data,created) SELECT ?,?,CAST(? AS BIGINT) WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized') ON CONFLICT(id) DO NOTHING").bind(v.id,JSON.stringify(v),Date.now()-i)),db.prepare("INSERT INTO settings (key,value) VALUES ('public',?) ON CONFLICT(key) DO NOTHING").bind(JSON.stringify(initialSettings)),db.prepare("INSERT INTO settings (key,value) VALUES ('initialized','1') ON CONFLICT(key) DO NOTHING")]);}
export async function content(){await seed();const db=database();const [rows,setting]=await Promise.all([db.prepare('SELECT data FROM videos ORDER BY created DESC').all<{data:string}>(),db.prepare("SELECT value FROM settings WHERE key='public'").first<{value:string}>()]);return {videos:await withViews(rows.results.map(r=>JSON.parse(r.data))),settings:setting?JSON.parse(setting.value):initialSettings}}
const encoder=new TextEncoder();
export function random(){return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function passwordHash(password:string,salt=random()){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:encoder.encode(salt),iterations:100000},key,256);return salt+':'+Array.from(new Uint8Array(bits)).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function credentials(){const saved=await database().prepare("SELECT value FROM settings WHERE key='credentials'").first<{value:string}>();return saved?JSON.parse(saved.value):{username:runtime().ADMIN_USERNAME,hash:runtime().ADMIN_PASSWORD_HASH}}
export async function verifyPassword(password:string,hash:string){if(!hash)return false;const actual=await passwordHash(password,hash.split(':')[0]);let result=actual.length^hash.length;for(let i=0;i<actual.length;i++)result|=actual.charCodeAt(i)^(hash.charCodeAt(i)||0);return result===0}
export function sessionToken(req:Request){return req.headers.get('cookie')?.match(/(?:^|;\s*)vp_session=([a-f0-9]{64})(?:;|$)/)?.[1]||''}
export async function authorized(req:Request){const token=sessionToken(req);return !!token&&!!await database().prepare('SELECT hash FROM sessions WHERE hash=? AND expires>?').bind(await digest(token),Date.now()).first()}
export function cookie(req:Request,value:string,maxAge=28800){return `vp_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export class UserError extends Error{constructor(message:string,public status=400){super(message)}}
export function sameOrigin(req:Request){if(req.headers.get('x-studio-request')!=='1'||(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin))throw new UserError('Please reload the studio and try again.',403)}
export function imageUrl(value:unknown){if(typeof value!=='string'||value.length>3000)return '';if(/^\/brands\/(cerave\.svg|airtel\.svg|black-white\.png)$/.test(value))return value;if(/^\/api\/media\/[a-f0-9]{64}\.(jpg|png|webp)$/.test(value))return value;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
export function profileUrl(value:unknown){if(!value)return '';try{const u=new URL(String(value));if(u.protocol!=='https:'||u.username||u.password||u.port||!['www.youtube.com','youtube.com','www.instagram.com','instagram.com'].includes(u.hostname))return '';return `https://${u.hostname.includes('youtube')?'www.youtube.com':'www.instagram.com'}${(u.pathname.startsWith('/channel/')?u.pathname:u.pathname.toLowerCase()).replace(/\/$/,'')}`}catch{return ''}}
